# Generated by Django 4.1.3 on 2022-11-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
    ]
