# Generated by Django 4.1.3 on 2022-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=500, unique=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("blood", models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name="MyUser",
        ),
    ]
