# Generated by Django 4.1.3 on 2022-11-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0003_doctor_document_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_logged_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.CharField(
                choices=[
                    ("Cardiologist", "Cardiologist"),
                    ("Dermatologists", "Dermatologists"),
                    (
                        "Emergency Medicine Specialists",
                        "Emergency Medicine Specialists",
                    ),
                    ("Allergists/Immunologists", "Allergists/Immunologists"),
                    ("Surgeon", "Surgeon"),
                ],
                max_length=255,
            ),
        ),
    ]
