# Generated by Django 4.1.3 on 2022-11-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
