# Generated by Django 4.1.3 on 2022-11-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0004_doctor_is_logged_in_alter_doctor_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="is_logged_in",
        ),
    ]
