# Generated by Django 4.1.3 on 2022-11-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0005_remove_doctor_is_logged_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_logged_in",
            field=models.BooleanField(default=False),
        ),
    ]
